baseURL = "https://www.naimcinar.com"
title = "naimcinar"
# Google Analytics 4 (GA4) - Direct integration
googleAnalytics = "G-XXXXXXXXXX"  # Replace with your GA4 Measurement ID
enableEmoji = true

theme = "hugo-coder"

enableGitInfo = false

languageCode = "en"
defaultContentLanguage = "en"

[pagination]
  pagerSize = 20

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

disqusShortname = "www-naimcinar-com"

[params]
    author = "Naim Cinar"
    description = "Naim Cinar's academic website"
    keywords = "blog,academic,advertising,personal"
    info = "(Ph.D.) Advertising and Public Relations"
    avatarURL = "images/avatar-naim.png"
    #gravatar = "john.doe@example.com"
    footerContent = "naimcinar.com"

    ShowDatesOnPosts = false

    dateFormat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = ""

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

  
  [[params.social]]
    name = "Instagram"
    icon = "fa-brands fa-instagram fa-2x"
    weight = 1
    url = "https://www.instagram.com/naimcinar/"
  [[params.social]]
    name = "AnadoluUniversity"
    icon = "fa-solid fa-university fa-2x"
    weight = 2
    url = "https://akademik.anadolu.edu.tr/naimcinar"
  [[params.social]]
    name = "Github"
    icon = "fa-brands fa-github fa-2x"
    weight = 3
    url = "https://github.com/nakiamo/"
  [[params.social]]
    name = "Twitter"
    icon = "fa-brands fa-x-twitter fa-2x"
    weight = 5
    url = "https://twitter.com/naimcinar/"
  [[params.social]]
    name = "Linkedin"
    icon = "fa-brands fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/naim-cinar-39116730/"
  [[params.social]]
    name = "RSS"
    icon = "fa-solid fa-rss fa-2x"
    weight = 8
    url = "https://www.naimcinar.com/index.xml"
    rel = "alternate"
    type = "application/rss+xml"


[languages]
    [languages.en]
        languageName = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Photography"
            weight = 3
            url = "https://naimc.myportfolio.com" 
            target="_blank"

            [[languages.en.menu.main]]
            name = "Teaching"
            weight = 4
            url = "teaching/"

            [[languages.en.menu.main]]
            name = "Publications"
            weight = 5
            url = "publications/"

            [[languages.en.menu.main]]
            name = "Contact"
            weight = 6
            url = "contact/"

            